version: '3.5'

services:
  postgres:
    container_name: postgres-local
    image: postgis/postgis:14-3.2-alpine
    ports:
      - '5432:5432'
    networks:
      - network
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: postgres-local
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  network:
    driver: bridge
    name: postgres-local

volumes:
  postgres_data:
    name: postgres-local
